"""Stable public error codes."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """V1 error codes exposed by JSON responses and SSE events."""

    THREAD_NOT_FOUND = "THREAD_NOT_FOUND"
    THREAD_BUSY = "THREAD_BUSY"
    MESSAGE_EMPTY = "MESSAGE_EMPTY"
    MODEL_REQUEST_FAILED = "MODEL_REQUEST_FAILED"
    MAX_AGENT_LOOPS_REACHED = "MAX_AGENT_LOOPS_REACHED"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_ARGUMENT_INVALID = "TOOL_ARGUMENT_INVALID"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    DUPLICATE_TOOL_CALL = "DUPLICATE_TOOL_CALL"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_ACCESS_DENIED = "FILE_ACCESS_DENIED"
    FILE_TYPE_UNSUPPORTED = "FILE_TYPE_UNSUPPORTED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_PARSE_FAILED = "FILE_PARSE_FAILED"
    OCR_NOT_SUPPORTED = "OCR_NOT_SUPPORTED"
    INVALID_FILENAME = "INVALID_FILENAME"
    ARTIFACT_TOO_LARGE = "ARTIFACT_TOO_LARGE"
    URL_NOT_ALLOWED = "URL_NOT_ALLOWED"
    WEB_SEARCH_FAILED = "WEB_SEARCH_FAILED"
    WEB_FETCH_FAILED = "WEB_FETCH_FAILED"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
